---
- hosts: moip
  remote_user: root
  
  vars:
  - localRepo: /usr/local/src/devops-challenge

  tasks:
  #http://docs.ansible.com/ansible/latest/git_module.html
  #checkout a github repo and use refspec to fetch all pull requests
  - git:
      repo: ssh://git@github.com/wendelmineiro89/devops-challenge.git
      dest: "{{ localRepo }}"
      refspec: '+refs/pull/*:refs/heads/*'

  #http://docs.ansible.com/ansible/latest/docker_container_module.html
  - name: "remove container"
    docker_container:
      name: lxcmoip
      state: absent

  - name: "create container mapping the war from git repo"
    docker_container:
      name: lxcmoip
      image: tomcat:8.0
      volumes:
        - /usr/local/src/devops-challenge/assets/java-chef-test.war:/usr/local/tomcat/webapps/java-chef-test.war
      ports:
        - "8080:8080"
