---
- hosts: moip
  remote_user: root
  tasks:
    - name: "Install basic software tomcat from repo"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - java-1.8.0-openjdk
        - tomcat
        - tomcat-native
        - unzip

    - name: "Auto-start at boot"
      service:
         name: tomcat
         state: started
         enabled: yes
